name: Build Android Debug APK

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Gradle (no wrapper)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      - name: Unzip project
        run: unzip GeoToolsGeoSulAndroid_vosk.zip -d appsrc

      - name: Build Debug APK
        run: cd appsrc && gradle :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: appsrc/app/build/outputs/apk/debug/*.apk
